# Generated by Django 5.1 on 2025-07-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('contact_number', models.CharField(max_length=15)),
                ('mobile_1', models.CharField(max_length=15)),
                ('mobile_2', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField()),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('standard', models.CharField(choices=[('jr_kg', 'Jr. KG'), ('sr_kg', 'Sr. KG'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th'), ('10', '10th'), ('11', '11th'), ('12', '12th')], max_length=10)),
                ('batch', models.CharField(max_length=100)),
                ('school_college', models.CharField(max_length=200)),
                ('previous_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stream', models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], max_length=20, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('preferred_course', models.CharField(max_length=100)),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('converted', 'Converted'), ('not_interested', 'Not Interested')], default='in_process', max_length=20)),
            ],
        ),
    ]
