# Generated by Django 5.1 on 2025-07-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='preferred_course',
            field=models.CharField(choices=[('jr_kg', 'Jr. KG'), ('sr_kg', 'Sr. KG'), ('1', '1st Standard'), ('2', '2nd Standard'), ('3', '3rd Standard'), ('4', '4th Standard'), ('5', '5th Standard'), ('6', '6th Standard'), ('7', '7th Standard'), ('8', '8th Standard'), ('9', '9th Standard'), ('10', '10th Standard'), ('11_science', '11th Standard - Science'), ('11_commerce', '11th Standard - Commerce'), ('11_arts', '11th Standard - Arts'), ('12_science', '12th Standard - Science'), ('12_commerce', '12th Standard - Commerce'), ('12_arts', '12th Standard - Arts')], max_length=20),
        ),
    ]
